### DISCUSSION TITLE
Use Read concern majority

### DISCUSSION THREAD

**Discussion by ppascualv** [mongodb/mongoid#5861] [Q&A] [answered]
I'm trying to configure my app using read concern majority. Doing that on mongoid.yml
```

      options:
        replica_set: whatever
        write:
          w: majority
        read:
          mode: secondary
        read_concern:
          level: majority
```

However like I'm using Atlas Search I'm getting this error:
`[72:InvalidOptions]: Command aggregate does not support { readConcern: { level: "majority", provenance: "clientSupplied" } } :: caused by :: Aggregation stage $search cannot run with a readConcern other than 'local'. Current readConcern: majority (on `

Is there a way to keep the configuration but change the reading concern only for the search queries?
