### DISCUSSION TITLE
Why is there not a way to set a config option that applies to all environments?

### DISCUSSION THREAD

**Discussion by AlvesJorge** [mongodb/mongoid#5950] [General]
Instead of
```
development:
  options:
    raise_not_found_error: false
    
staging:
  options:
    raise_not_found_error: false
    
production:
  options:
    raise_not_found_error: false
```
we could write:
```
default:
  options:
    raise_not_found_error: false
```

It's such an obvious feature that it must have been thought about at some point, I'm wondering why it was never integrated.
